---
- name: Praparando o ambiente de trabalho
  hosts: localhost
  user: root
  
  tasks:
    
    - name: Instalando apps uteis
      become: true
      apt:
        name: '{{ item }}'
        install_recommends: yes
        state: present
      loop:
          - vim
          - curl
          - wget
          - tree
          - python3-pip
          - git
          - bash-completion
          - flameshot
          - virtualbox
          - jq

    - block:
      
      - name: Instalando Microsoft Key
        become: true
        apt_key:
          url: 'https://packages.microsoft.com/keys/microsoft.asc'
          state: present
      
      - name: Instalando VSCode Repository
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
          state: present
          filename: vscode
    
      - name: Instalando Visual Studio Code
        become: true
        apt:
          name: code

      - name: Instalando Virtual Studio Code Extensions
        shell:
          cmd: code --install-extension '{{ item }}'
        loop:
          - redhat.ansible
          - redhat.vscode-yaml
          - ms-vscode-remote.remote-ssh
          - vivaxy.vscode-conventional-commits

    - block:
      - name: Instalando Terraform 1.3.3
        become: true
        unarchive:
          src: 'https://releases.hashicorp.com/terraform/1.3.3/terraform_1.3.3_linux_amd64.zip'
          dest: /usr/local/bin
          remote_src: yes
    
    - block: 
      - name: Instalando Docker Key
        become: true
        apt_key:
          url: 'https://download.docker.com/linux/debian/gpg'
          state: present

      - name: Instalando Docker Repository
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable'
          state: present
          filename: docker-ce

      - name: Instalando Docker
        become: true
        apt:
          name: docker-ce

      - name: Adicionando usuario atual no grupo do docker
        become: yes
        user: 
          name: '{{ ansible_user_id }}'
          groups: docker 
          append: yes

      - name: Instalando Docker Machine
        become: true
        get_url:
          url: 'https://raw.githubusercontent.com/docker/machine/v0.16.0/contrib/completion/bash/docker-machine.bash'
          dest: '/etc/bash_completion.d/docker-machine'
              
    - block:
      - name: Instalando Kubectl 1.25.0
        become: true
        get_url:    
          url: 'https://dl.k8s.io/release/v1.25.0/bin/linux/amd64/kubectl'
          dest: /usr/local/bin/kubectl
          mode: 755
...