---
- name: Praparando o ambiente de trabalho
  hosts: localhost
  become: true
  user: root
  
  tasks:
    
    - name: Instalando apps uteis
      become: true
      apt:
        name: '{{ item }}'
        install_recommends: yes
        state: present
      loop:
          - vim
          - curl
          - wget
          - nmap
          - tree
          - python3-pip
          - git
          - openjdk-17-jdk
          - bash-completion
          - flameshot
          - virtualbox
          - jq
          - vlc
          - terminator

    - block:
      
      - name: Instalando Microsoft Key
        become: true
        apt_key:
          url: 'https://packages.microsoft.com/keys/microsoft.asc'
          state: present
      
      - name: Instalando VSCode Repository
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
          state: present
          filename: vscode
    
      - name: Instalando Visual Studio Code
        become: true
        apt:
          name: code

    - block:
      - name: Instalando Terraform 1.10.5
        become: true
        unarchive:
          src: 'https://releases.hashicorp.com/terraform/1.10.5/terraform_1.10.5_linux_amd64.zip'
          dest: /usr/local/bin
          remote_src: yes

    - name: Instalando Virtual Studio Code Extensions
      shell: code --install-extension '{{ item }}' --no-sandbox --user-data-dir=/home/{{ ansible_user_id }}/.vscode
      loop:
        - redhat.ansible
        - redhat.vscode-yaml
        - ms-vscode-remote.remote-ssh
        - vivaxy.vscode-conventional-commits
        - gencay.vscode-chatgpt
        - HashiCorp.terraform
    
    - block: 
      - name: Instalando Docker Key
        become: true
        apt_key:
          url: 'https://download.docker.com/linux/debian/gpg'
          state: present

      - name: Instalando Docker Repository
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable'
          state: present
          filename: docker-ce

      - name: Instalando Docker
        become: true
        apt:
          name: docker-ce

      - name: Adicionando usuario atual no grupo do docker
        become: yes
        user: 
          name: '{{ ansible_user_id }}'
          groups: docker 
          append: yes

      - name: Instalando Docker Machine
        become: true
        get_url:
          url: 'https://raw.githubusercontent.com/docker/machine/v0.16.2/contrib/completion/bash/docker-machine.bash'
          dest: '/etc/bash_completion.d/docker-machine'
              
    - block:
      - name: Instalando Kubectl 1.26.0
        become: true
        get_url:    
          url: 'https://dl.k8s.io/release/v1.26.0/bin/linux/amd64/kubectl'
          dest: /usr/local/bin/kubectl
          mode: 755

    - name: Instalando Obsidian
      ansible.builtin.apt:
        deb: https://github.com/obsidianmd/obsidian-releases/releases/download/v1.6.7/obsidian_1.6.7_amd64.deb
      become: true

    - name: Instalar dependências necessárias para o vmware
      apt:
        name:
          - build-essential
          - linux-headers-generic

    - name: Baixando o VMware Player
      get_url:
        url: https://softwareupdate.vmware.com/cds/vmw-desktop/player/17.6.2/24409262/linux/core/VMware-Player-17.6.2-24409262.x86_64.bundle.tar
        dest: /tmp/VMware-Player.tar

    - name: Descompactando o arquivo baixado
      command: tar -xvf /tmp/VMware-Player.tar -C /tmp

    - name: Tornando o arquivo executável
      command: chmod +x /tmp/VMware-Player-17.6.2-24409262.x86_64.bundle

    - name: Executando o instalador do VMware Player
      command: /tmp/VMware-Player-17.6.2-24409262.x86_64.bundle --console --required --eulas-agreed

...
